title: me
author: stephyi
email: shiro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  abut myself.

# social links
twitter_username: wakeanda # DO NOT include the @ character, or else the build will fail!
github_username:  stephyi # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
